// Inhalte des Online-Anamnesebogens (Gesundheits- und Ernährungsfragebogen).
// Aufbau seit Version 3.0 (BIO-15): Kontaktdaten vorab, danach Themenfelder in
// fester Reihenfolge — Notfall, aktuelle Beschwerden, Familiengeschichte, dann
// die einzelnen Körpersysteme, zuletzt Labor/Ziele. Jedes Körpersystem endet
// mit einem "meds"-Feld; alle diese Einträge laufen automatisch in der
// Zusammenfassung am Ende zusammen.
// Inhaltliche Änderungen (Text/Felder) laufen über BIO-15.

import { site } from "@/content/site";

export type FieldType =
  | "text"
  | "textarea"
  | "check"
  | "radiotext"
  | "scale"
  | "table"
  | "meds"
  | "note";

interface FieldBase {
  name: string;
  label: string;
  hint?: string;
}

export interface TextField extends FieldBase {
  type: "text";
  placeholder?: string;
}

export interface TextareaField extends FieldBase {
  type: "textarea";
  lines?: number;
}

export interface CheckField extends FieldBase {
  type: "check";
  cols: 1 | 2 | 3;
  options: string[];
  other?: boolean;
}

export interface RadioTextField extends FieldBase {
  type: "radiotext";
  options?: string[];
  withText?: boolean;
  textPlaceholder?: string;
}

export interface ScaleField extends FieldBase {
  type: "scale";
  lowLabel?: string;
  highLabel?: string;
}

export interface TableField extends FieldBase {
  type: "table";
  columns: string[];
  rows?: number;
}

/**
 * Abschluss-Frage eines Themenfeldes: "Nehmen Sie in diesem Bereich
 * Medikamente oder Nahrungsergänzungsmittel?" plus Tabelle. Alle meds-Felder
 * werden am Ende des Bogens automatisch zu einer Übersicht zusammengeführt.
 */
export interface MedsField extends FieldBase {
  type: "meds";
  /** Kurzform des Themenfeldes für die Spalte "Bereich" in der Zusammenfassung. */
  area: string;
  rows?: number;
}

export interface NoteField {
  type: "note";
  tone: "info" | "warn";
  title: string;
  text: string;
}

export type Field =
  | TextField
  | TextareaField
  | CheckField
  | RadioTextField
  | ScaleField
  | TableField
  | MedsField
  | NoteField;

export interface Section {
  /** Anker-Id und stabiler Schlüssel. */
  key: string;
  /** Nummer des Themenfeldes; null = Vorab-/Abschlussblock ohne Nummer. */
  n: number | null;
  title: string;
  /** Kurzlabel für die Sprungnavigation. */
  short: string;
  bodymap?: boolean;
  fields: Field[];
}

export const medsColumns = ["Präparat / Wirkstoff", "Art (M / N)", "Dosierung", "seit wann", "Grund / Wirkung"];

export const medsSummaryColumns = ["Themenfeld", ...medsColumns];

export const medsQuestionLabel = "Nehmen Sie in diesem Bereich aktuell Medikamente oder Nahrungsergänzungsmittel?";

export const medsHint =
  "Art: M = Medikament, N = Nahrungsergänzungsmittel. Alle Einträge erscheinen automatisch in der Zusammenfassung am Ende des Bogens.";

export const bodyMapCategories = [
  { key: "schmerz", label: "Schmerz", sym: "X", color: "#B5652F" },
  { key: "verspannung", label: "Verspannung", sym: "O", color: "#3F5744" },
  { key: "kribbeln", label: "Kribbeln / Taubheit", sym: "~", color: "#A67C2E" },
  { key: "sonstiges", label: "Sonstiges", sym: "•", color: "#6B6560" },
] as const;

export type BodyMapCategoryKey = (typeof bodyMapCategories)[number]["key"];

export const sections: Section[] = [
  {
    key: "kontakt",
    n: null,
    short: "Kontaktdaten",
    title: "Ihre Kontaktdaten",
    fields: [
      { type: "text", label: "Vor- und Nachname", name: "k_name" },
      { type: "text", label: "Geburtsdatum / Alter", name: "k_geb" },
      { type: "text", label: "Adresse", name: "k_adresse" },
      { type: "text", label: "Telefonnummer", name: "k_tel" },
      { type: "text", label: "E-Mail-Adresse", name: "k_email" },
      { type: "text", label: "Körpergröße", name: "k_groesse" },
      { type: "text", label: "Aktuelles Gewicht", name: "k_gewicht" },
      {
        type: "check",
        label: "Gewichtsverlauf der letzten 12 Monate",
        name: "k_gewichtsverlauf",
        cols: 3,
        options: ["stabil", "Zunahme", "Abnahme"],
      },
      { type: "text", label: "Veränderung (falls zutreffend)", name: "k_gewicht_veraenderung" },
      { type: "text", label: "Hausarzt / behandelnde Ärzte / Therapeuten", name: "k_hausarzt" },
      { type: "text", label: "Notfallkontakt, falls gewünscht", name: "k_notfallkontakt" },
    ],
  },
  {
    key: "t1",
    n: 1,
    short: "Notfall",
    title: "Notfall und akute Sicherheit",
    fields: [
      {
        type: "note",
        tone: "warn",
        title: "Wichtiger Hinweis",
        text: "Dieser Bogen ersetzt keine ärztliche Abklärung und keine Notfallversorgung. Bei akuten, starken, neu auftretenden oder sich rasch verschlechternden Beschwerden wenden Sie sich bitte an den Hausarzt, den ärztlichen Bereitschaftsdienst oder in Notfällen an den Notruf 112.",
      },
      {
        type: "check",
        label: "Bitte kreuzen Sie an, wenn aktuell oder kürzlich eines der folgenden Symptome besteht/bestand",
        name: "t1_symptome",
        cols: 2,
        options: [
          "akute starke Schmerzen",
          "Brustschmerz / Engegefühl",
          "Atemnot",
          "Ohnmacht / Bewusstseinsstörung",
          "Blut im Stuhl oder Urin",
          "schwarzer Stuhl",
          "ungewollter starker Gewichtsverlust",
          "anhaltendes Fieber",
          "starke neurologische Symptome",
          "Suizidgedanken",
          "starke allergische Reaktion",
          "Schwangerschaft mit akuten Beschwerden",
          "keines davon",
          "ärztlich bereits abgeklärt",
        ],
      },
      {
        type: "textarea",
        label: "Falls Sie etwas angekreuzt haben: Bitte beschreiben Sie kurz, was genau vorliegt und ob bereits eine ärztliche Abklärung erfolgt ist.",
        name: "t1_beschreibung",
        lines: 3,
      },
      {
        type: "check",
        label: "Bestehen bekannte notfallrelevante Erkrankungen?",
        name: "t1_notfall_diagnosen",
        hint: "Damit ich weiß, worauf im Termin zu achten ist.",
        cols: 2,
        other: true,
        options: [
          "keine bekannt",
          "schwere Allergie / Anaphylaxie",
          "Asthma",
          "Epilepsie / Krampfanfälle",
          "Diabetes mit Unterzuckerungen",
          "Herzerkrankung",
          "Blutgerinnungsstörung",
          "Ohnmachts- / Kreislaufneigung",
        ],
      },
      {
        type: "radiotext",
        label: "Notfallausweis, Allergiepass oder Notfallmedikament vorhanden?",
        name: "t1_notfallausweis",
        options: ["nein", "ja"],
        textPlaceholder: "welcher / welches (z. B. Adrenalin-Pen, Asthmaspray)",
      },
      {
        type: "radiotext",
        label: "Sind Sie aktuell schwanger oder stillen Sie?",
        name: "t1_schwangerschaft",
        options: ["nein", "schwanger", "stillend", "möglich / unklar"],
        textPlaceholder: "Schwangerschaftswoche oder Alter des Kindes",
      },
    ],
  },
  {
    key: "t2",
    n: 2,
    short: "Beschwerden",
    title: "Aktuelle Beschwerden",
    bodymap: true,
    fields: [
      {
        type: "textarea",
        label: "Was ist der Hauptgrund für Ihre Beratung? Bitte beschreiben Sie Ihr Anliegen in eigenen Worten.",
        name: "t2_hauptgrund",
        lines: 4,
      },
      {
        type: "table",
        label: "Welche drei Themen sind aktuell am wichtigsten für Sie?",
        name: "t2_top3",
        columns: ["#", "Thema"],
        rows: 3,
      },
      { type: "scale", label: "Wie stark belastet Sie das aktuell?", name: "t2_belastung", lowLabel: "gar nicht", highLabel: "sehr stark" },
      {
        type: "check",
        label: "Seit wann besteht Ihr Hauptthema?",
        name: "t2_seitwann",
        cols: 2,
        options: ["Tage", "Wochen", "Monate", "Jahre"],
      },
      { type: "text", label: "Genauer Beginn, falls bekannt", name: "t2_beginn" },
      {
        type: "note",
        tone: "info",
        title: "Ausfüllhilfe zur Körperkarte",
        text: "Wählen Sie oben eine Kategorie und tippen Sie dann auf die Stelle im Körper, an der Sie etwas spüren. Nochmaliges Tippen entfernt die Markierung wieder.",
      },
      {
        type: "table",
        label: "Ihre wichtigsten Beschwerden im Überblick",
        name: "t2_symptome",
        hint: "Seit wann, wie stark, was macht es besser oder schlechter.",
        columns: ["Beschwerde", "Seit wann?", "Stärke 0–10", "Auslöser / Muster", "Besser / schlechter durch"],
        rows: 5,
      },
      {
        type: "check",
        label: "Allgemeine Symptome",
        name: "t2_allgemein",
        cols: 3,
        other: true,
        options: [
          "Müdigkeit",
          "Erschöpfung",
          "Brain Fog",
          "Konzentrationsprobleme",
          "Schwindel",
          "Kopfschmerzen",
          "Migräne",
          "Herzklopfen",
          "Atembeschwerden",
          "Wassereinlagerungen",
          "Nachtschweiß",
          "Fiebergefühl",
          "Frieren",
          "Hitzegefühl",
          "Heißhunger",
          "Appetitlosigkeit",
          "ungewollte Gewichtsveränderung",
        ],
      },
      {
        type: "check",
        label: "Wie haben sich Ihre Beschwerden entwickelt?",
        name: "t2_verlauf",
        cols: 3,
        options: [
          "plötzlich begonnen",
          "schleichend begonnen",
          "seit Beginn ähnlich",
          "zunehmend stärker",
          "in Schüben",
          "wechselnd",
          "zyklusabhängig",
          "stressabhängig",
          "ernährungsabhängig",
          "belastungsabhängig",
          "jahreszeitlich",
          "unklar",
        ],
      },
      {
        type: "check",
        label: "Mögliche Auslöser oder Ereignisse vor Beginn/Verschlechterung",
        name: "t2_ausloeser",
        cols: 2,
        other: true,
        options: [
          "Infekt",
          "Antibiotika",
          "neues Medikament",
          "Hormonpräparat / Pille",
          "Impfung",
          "Operation / Narkose",
          "Unfall / Verletzung",
          "Schwangerschaft / Geburt",
          "starke Stressphase",
          "Trauer / emotionale Belastung",
          "Umzug / Arbeitsplatzwechsel",
          "Diät / Ernährungsumstellung",
          "Auslandsreise",
          "Schimmel / Umweltbelastung",
          "Zahnbehandlung",
        ],
      },
      {
        type: "textarea",
        label: "Gab es bessere oder schlechtere Phasen? Was war in diesen Phasen anders?",
        name: "t2_verlauf_text",
        lines: 3,
      },
      {
        type: "table",
        label: "Bereits gestellte Diagnosen",
        name: "t2_diagnosen",
        hint: "Nur das, was ärztlich festgestellt wurde. Beschwerden ohne Diagnose gehören in die Tabelle oben.",
        columns: ["Diagnose", "Seit wann?", "Behandlung", "Aktueller Status"],
        rows: 4,
      },
      {
        type: "table",
        label: "Operationen / Krankenhausaufenthalte",
        name: "t2_ops",
        columns: ["Operation / Aufenthalt", "Jahr", "Grund", "Auffälligkeiten danach?"],
        rows: 3,
      },
      {
        type: "textarea",
        label: "Unfälle, Verletzungen, Narben oder länger bestehende körperliche Einschränkungen",
        name: "t2_unfaelle",
        lines: 3,
      },
    ],
  },
  {
    key: "t3",
    n: 3,
    short: "Familie",
    title: "Familiengeschichte und Veranlagung",
    fields: [
      {
        type: "note",
        tone: "info",
        title: "Freiwillige Angabe",
        text: "Diese Angaben helfen bei der Einschätzung erblicher Veranlagungen. Bitte ohne Namen, nur Verwandtschaftsgrad. Sie können den Abschnitt auch frei lassen.",
      },
      {
        type: "table",
        label: "Erkrankungen in der Familie",
        name: "t3_familienanamnese",
        columns: ["Erkrankung", "Verwandtschaftsgrad (z. B. Mutter, Vater, Geschwister)", "Alter bei Diagnose (falls bekannt)"],
        rows: 4,
      },
      {
        type: "check",
        label: "In der Familie bekannt",
        name: "t3_familie_bekannt",
        cols: 2,
        other: true,
        options: [
          "keine bekannt",
          "Bluthochdruck",
          "Herzinfarkt oder Schlaganfall vor dem 60. Lebensjahr",
          "Diabetes Typ 2",
          "Diabetes Typ 1",
          "Fettstoffwechselstörung / hohes Cholesterin",
          "starkes Übergewicht",
          "Schilddrüsenerkrankung",
          "Autoimmunerkrankung",
          "Zöliakie",
          "chronisch-entzündliche Darmerkrankung",
          "Rheuma / Gelenkerkrankungen",
          "Osteoporose",
          "Demenz",
          "Depression / Angsterkrankung",
          "Allergien, Asthma oder Neurodermitis",
          "Lipödem / Lymphödem",
          "Thrombosen / Gerinnungsstörung",
          "Nierenerkrankung",
          "Suchterkrankung",
        ],
      },
      {
        type: "check",
        label: "Tumor- / Krebserkrankung",
        name: "t3_tumor",
        hint: "Freiwillige Angabe als Hintergrundinformation für das Beratungsgespräch — keine Diagnosestellung.",
        cols: 1,
        other: true,
        options: [
          "keine bekannt",
          "eigene Vorgeschichte (aktuell oder früher)",
          "in der Familie bekannt (z. B. Eltern, Geschwister)",
        ],
      },
      {
        type: "radiotext",
        label: "Wurden bei Ihnen genetische Untersuchungen durchgeführt?",
        name: "t3_gentest",
        options: ["nein", "ja", "unklar"],
        textPlaceholder: "z. B. Hämochromatose, Faktor-V-Leiden, MTHFR, Zöliakie-Typisierung",
      },
    ],
  },
  {
    key: "t4",
    n: 4,
    short: "Bewegungsapparat",
    title: "Bewegungsapparat (orthopädische Beschwerden)",
    fields: [
      {
        type: "check",
        label: "Bekannte Diagnosen in diesem Bereich",
        name: "t4_diagnosen",
        cols: 2,
        other: true,
        options: [
          "keine bekannt",
          "Arthrose",
          "Bandscheibenvorfall",
          "Skoliose / Fehlhaltung",
          "Osteoporose",
          "Rheuma / entzündliche Gelenkerkrankung",
          "Gicht",
          "Sehnenentzündung / Tendinitis",
          "Karpaltunnelsyndrom",
          "Hypermobilität",
          "Kiefergelenkbeschwerden (CMD)",
          "Fußfehlstellung",
          "Bandscheiben- oder Gelenk-OP",
        ],
      },
      {
        type: "check",
        label: "Wo bestehen Schmerzen oder Beschwerden?",
        name: "t4_bereiche",
        cols: 3,
        other: true,
        options: [
          "Nacken",
          "Rücken oben",
          "Rücken unten",
          "Schulter",
          "Ellenbogen",
          "Handgelenk / Hand",
          "Kiefer",
          "Hüfte",
          "Knie",
          "Sprunggelenk / Fuß",
          "mehrere Gelenke",
          "Muskelschmerzen",
          "Sehnen / Ansätze",
          "Taubheit / Kribbeln",
          "Schwächegefühl",
        ],
      },
      {
        type: "table",
        label: "Schmerzen im Detail",
        name: "t4_schmerz_tabelle",
        columns: ["Bereich", "Seit wann?", "Stärke 0–10", "Auslöser", "Besser / schlechter durch"],
        rows: 3,
      },
      {
        type: "check",
        label: "Bewegung aktuell",
        name: "t4_bewegung",
        cols: 2,
        other: true,
        options: [
          "kaum Bewegung",
          "Spaziergänge",
          "Krafttraining",
          "Ausdauertraining",
          "Yoga / Pilates",
          "Vereinssport",
          "körperliche Arbeit",
          "Reha / Physiotherapie",
        ],
      },
      { type: "text", label: "Trainingshäufigkeit pro Woche", name: "t4_haeufigkeit" },
      { type: "text", label: "Schritte / Alltagsbewegung", name: "t4_schritte" },
      {
        type: "check",
        label: "Regeneration nach Belastung",
        name: "t4_regeneration",
        cols: 3,
        options: ["gut", "mittel", "schlecht", "sehr wechselnd"],
      },
      {
        type: "textarea",
        label: "Verletzungen, Operationen oder Narben, die mit den Beschwerden zusammenhängen könnten",
        name: "t4_verletzungen",
        lines: 3,
      },
      { type: "meds", label: medsQuestionLabel, name: "t4_meds", area: "Bewegungsapparat", hint: "z. B. Schmerzmittel, Cortison, Kollagen, Magnesium, Vitamin D" },
    ],
  },
  {
    key: "t5",
    n: 5,
    short: "Verdauung",
    title: "Verdauungssystem, Ernährung und Verträglichkeiten",
    fields: [
      {
        type: "check",
        label: "Bekannte Diagnosen in diesem Bereich",
        name: "t5_diagnosen",
        cols: 2,
        other: true,
        options: [
          "keine bekannt",
          "Reizdarmsyndrom",
          "Zöliakie",
          "Morbus Crohn",
          "Colitis ulcerosa",
          "Divertikel",
          "Refluxkrankheit",
          "Gastritis / Helicobacter",
          "Gallensteine / Gallenblase entfernt",
          "Fettleber",
          "Bauchspeicheldrüsen-Thema",
          "SIBO / Dünndarmfehlbesiedlung",
          "Pilzbesiedlung (Candida)",
          "Hämorrhoiden",
        ],
      },
      {
        type: "check",
        label: "Stuhlgang: Häufigkeit",
        name: "t5_haeufigkeit",
        cols: 3,
        options: ["mehrmals täglich", "täglich", "alle 2 Tage", "seltener", "wechselnd"],
      },
      {
        type: "check",
        label: "Stuhlgang: Konsistenz",
        name: "t5_konsistenz",
        cols: 3,
        options: ["hart", "geformt", "weich", "breiig", "flüssig", "wechselnd"],
      },
      {
        type: "check",
        label: "Auffälligkeiten und Beschwerden",
        name: "t5_auffaelligkeiten",
        cols: 2,
        other: true,
        options: [
          "Blähbauch",
          "Blähungen",
          "Bauchschmerzen",
          "Krämpfe",
          "Übelkeit",
          "Reflux / Sodbrennen",
          "Völlegefühl",
          "frühe Sättigung",
          "Durchfall",
          "Verstopfung",
          "Schleim im Stuhl",
          "Blut im Stuhl",
          "schwarzer Stuhl",
          "fettig / glänzend",
          "auffälliger Geruch",
          "unverdaute Nahrung",
          "Afterjucken",
          "Nahrungsmittelreaktionen",
        ],
      },
      {
        type: "check",
        label: "Wann treten die Beschwerden besonders auf?",
        name: "t5_wann",
        cols: 3,
        other: true,
        options: [
          "direkt nach dem Essen",
          "1–3 Stunden nach dem Essen",
          "abends",
          "nachts",
          "morgens",
          "zyklusabhängig",
          "stressabhängig",
          "nach bestimmten Lebensmitteln",
          "nach Sport",
          "nach Alkohol",
          "nach Kaffee",
          "unklar",
        ],
      },
      {
        type: "check",
        label: "Was vertragen Sie schlecht?",
        name: "t5_vertraeglichkeit",
        hint: "Früher als acht einzelne Skalen abgefragt — jetzt einfach ankreuzen.",
        cols: 3,
        other: true,
        options: [
          "nichts davon",
          "Milchprodukte",
          "Gluten / Getreide",
          "Obst",
          "Rohkost",
          "Hülsenfrüchte",
          "Kohlgemüse",
          "Zwiebeln / Knoblauch",
          "fettige Speisen",
          "scharfe Speisen",
          "Kaffee",
          "Alkohol",
          "Zucker / Süßigkeiten",
          "Fertigprodukte",
        ],
      },
      {
        type: "check",
        label: "Ärztlich festgestellte Unverträglichkeiten",
        name: "t5_unvertraeglichkeiten",
        cols: 3,
        other: true,
        options: ["keine", "Gluten", "Laktose", "Fruktose", "Histamin", "Sorbit", "FODMAPs", "Eier", "Nüsse", "Soja"],
      },
      {
        type: "textarea",
        label: "Bitte beschreiben Sie bekannte Reaktionen auf Lebensmittel genauer (was, wie schnell, wie stark).",
        name: "t5_reaktionen",
        lines: 3,
      },
      {
        type: "check",
        label: "Aktuelle Ernährungsform",
        name: "t5_form",
        cols: 2,
        other: true,
        options: [
          "Mischkost",
          "vegetarisch",
          "vegan",
          "glutenfrei",
          "laktosefrei",
          "histaminarm",
          "low carb",
          "ketogen",
          "kalorienreduziert",
          "Intervallfasten",
          "intuitiv",
          "keine bestimmte Ernährungsform",
        ],
      },
      {
        type: "textarea",
        label: "Typischer Ernährungstag: Frühstück, Mittagessen, Abendessen, Snacks, Getränke",
        name: "t5_typischer_tag",
        lines: 4,
      },
      { type: "text", label: "Wasser / ungesüßte Getränke pro Tag", name: "t5_wasser" },
      { type: "text", label: "Kaffee / koffeinhaltige Getränke", name: "t5_kaffee" },
      { type: "text", label: "Süßigkeiten / Snacks / stark verarbeitete Lebensmittel", name: "t5_suessigkeiten" },
      { type: "text", label: "Essrhythmus / Mahlzeitenabstände", name: "t5_essrhythmus" },
      {
        type: "text",
        label: "Praktische Rahmenbedingungen (Budget, Kochzeit, Verfügbarkeit)",
        name: "t5_rahmenbedingungen",
        hint: "Hilft, Empfehlungen alltagstauglich zu gestalten.",
      },
      {
        type: "textarea",
        label: "Gibt es Essverhalten, Diäten oder Einschränkungen, die für die Beratung wichtig sind?",
        name: "t5_diaeten",
        lines: 3,
      },
      { type: "meds", label: medsQuestionLabel, name: "t5_meds", area: "Verdauung & Ernährung", hint: "z. B. Säureblocker, Abführmittel, Enzyme, Probiotika, Eisen, B12" },
    ],
  },
  {
    key: "t6",
    n: 6,
    short: "Nervensystem",
    title: "Nervensystem, Psyche und Schlaf",
    fields: [
      {
        type: "check",
        label: "Bekannte Diagnosen in diesem Bereich",
        name: "t6_diagnosen",
        cols: 2,
        other: true,
        options: [
          "keine bekannt",
          "Migräne",
          "Spannungskopfschmerz",
          "Epilepsie",
          "Polyneuropathie",
          "Multiple Sklerose",
          "Restless Legs",
          "Depression",
          "Angst- / Panikstörung",
          "ADHS",
          "Burnout / Erschöpfungsdepression",
          "Schlafapnoe",
          "Tinnitus",
        ],
      },
      {
        type: "check",
        label: "Neurologische Beobachtungen",
        name: "t6_neuro",
        cols: 2,
        other: true,
        options: [
          "Taubheit / Kribbeln",
          "Zittern",
          "Gangunsicherheit",
          "Sehstörungen",
          "Schwindel",
          "Gedächtnisprobleme",
          "Wortfindungsstörungen",
          "veränderter Geruchs- oder Geschmackssinn",
          "Ohrgeräusche",
          "Licht- oder Geräuschempfindlichkeit",
          "Krampfanfälle",
        ],
      },
      { type: "scale", label: "Energielevel tagsüber", name: "t6_energie", lowLabel: "sehr niedrig", highLabel: "sehr hoch" },
      { type: "scale", label: "Aktuelle Stressbelastung", name: "t6_stress", lowLabel: "keine", highLabel: "sehr hoch" },
      { type: "scale", label: "Schlafqualität", name: "t6_schlafqualitaet", lowLabel: "sehr schlecht", highLabel: "sehr gut" },
      { type: "text", label: "Schlafdauer durchschnittlich", name: "t6_schlafdauer" },
      { type: "text", label: "Einschlafzeit / Aufwachzeit", name: "t6_zeiten" },
      {
        type: "text",
        label: "Bildschirmzeit am Abend vor dem Schlafengehen",
        name: "t6_bildschirmzeit",
        hint: "z. B. Handy/PC/TV in der letzten Stunde vor dem Einschlafen.",
      },
      {
        type: "check",
        label: "Wann ist Ihre Energie am niedrigsten?",
        name: "t6_energie_tief",
        cols: 2,
        options: [
          "morgens",
          "vormittags",
          "nach dem Essen",
          "nachmittags",
          "abends",
          "wechselnd",
          "nach Sport",
          "nach Stress",
          "zyklusabhängig",
          "unklar",
        ],
      },
      {
        type: "check",
        label: "Müdigkeit und Leistungsfähigkeit",
        name: "t6_muedigkeit",
        cols: 2,
        other: true,
        options: [
          "bleierne Müdigkeit",
          "Einschlafen tagsüber",
          "Brain Fog",
          "Konzentrationsprobleme",
          "Antriebslosigkeit",
          "körperliche Schwäche",
          "Leistungseinbruch beim Sport",
          "Erschöpfung nach Belastung",
          "lange Regenerationszeit",
        ],
      },
      {
        type: "check",
        label: "Schlafprobleme",
        name: "t6_schlafprobleme",
        cols: 2,
        other: true,
        options: [
          "Einschlafprobleme",
          "Durchschlafprobleme",
          "frühes Erwachen",
          "Nachtschweiß",
          "Herzklopfen nachts",
          "nächtliches Wasserlassen",
          "unruhige Beine",
          "Zähneknirschen",
          "nicht erholt trotz Schlaf",
          "Albträume",
          "Schnarchen",
        ],
      },
      {
        type: "check",
        label: "Stressquellen und emotionales Erleben",
        name: "t6_stressquellen",
        cols: 2,
        other: true,
        options: [
          "Arbeit",
          "Familie",
          "Beziehung",
          "finanzielle Themen",
          "Gesundheitssorgen",
          "Pflege / Verantwortung",
          "Prüfung / Studium",
          "Schlafmangel",
          "innere Unruhe",
          "Reizbarkeit",
          "Angst / Panik",
          "depressive Verstimmung",
          "Stimmungsschwankungen",
          "Überforderung",
          "starkes Grübeln",
        ],
      },
      { type: "textarea", label: "Was tut Ihnen spürbar gut? Was raubt Ihnen Energie?", name: "t6_gut_schlecht", lines: 3 },
      { type: "meds", label: medsQuestionLabel, name: "t6_meds", area: "Nervensystem & Schlaf", hint: "z. B. Schlafmittel, Antidepressiva, Migränemittel, Magnesium, Ashwagandha" },
    ],
  },
  {
    key: "augen_ohren",
    n: 7,
    short: "Augen & Ohren",
    title: "Augen und Ohren",
    fields: [
      {
        type: "check",
        label: "Bekannte Diagnosen in diesem Bereich",
        name: "augen_ohren_diagnosen",
        cols: 2,
        other: true,
        options: [
          "keine bekannt",
          "grauer Star (Katarakt)",
          "grüner Star (Glaukom)",
          "Makuladegeneration",
          "trockene Augen / Sicca-Syndrom",
          "Hörsturz",
          "Morbus Menière",
          "chronische Mittelohrentzündung",
          "Tinnitus",
          "Schwerhörigkeit",
        ],
      },
      {
        type: "check",
        label: "Beobachtungen zu Augen und Ohren",
        name: "augen_ohren_beobachtungen",
        cols: 2,
        other: true,
        options: [
          "keine",
          "Sehstörungen",
          "verschwommenes Sehen",
          "Lichtempfindlichkeit",
          "trockene / brennende Augen",
          "tränende Augen",
          "Ohrgeräusche / Tinnitus",
          "Hörminderung",
          "Druckgefühl im Ohr",
          "Schwindel",
          "Ohrenschmerzen",
          "häufige Ohrenentzündungen",
        ],
      },
      {
        type: "textarea",
        label: "Weitere Beobachtungen zu Augen oder Ohren",
        name: "augen_ohren_weitere",
        lines: 2,
      },
      {
        type: "meds",
        label: medsQuestionLabel,
        name: "augen_ohren_meds",
        area: "Augen & Ohren",
        hint: "z. B. Augentropfen, künstliche Tränenflüssigkeit, Ginkgo, Zink, Magnesium",
      },
    ],
  },
  {
    key: "t7",
    n: 8,
    short: "Atemwege",
    title: "Atemwege und Lunge",
    fields: [
      {
        type: "check",
        label: "Bekannte Diagnosen in diesem Bereich",
        name: "t7_diagnosen",
        cols: 2,
        other: true,
        options: [
          "keine bekannt",
          "Asthma",
          "COPD / chronische Bronchitis",
          "Heuschnupfen / allergische Rhinitis",
          "chronische Nebenhöhlenentzündung",
          "Nasenpolypen",
          "Schlafapnoe",
          "Lungenentzündung in den letzten 2 Jahren",
          "Long Covid / Post Covid",
        ],
      },
      {
        type: "check",
        label: "Beschwerden der Atemwege",
        name: "t7_symptome",
        cols: 2,
        other: true,
        options: [
          "keine",
          "Husten",
          "Auswurf / Schleim",
          "Atemnot in Ruhe",
          "Atemnot bei Belastung",
          "Kurzatmigkeit beim Treppensteigen",
          "häufiges Räuspern",
          "verstopfte oder laufende Nase",
          "häufiges Niesen",
          "Schnarchen",
          "nächtliche Atemaussetzer",
          "Engegefühl in der Brust",
          "Heiserkeit",
          "häufige Erkältungen",
        ],
      },
      {
        type: "radiotext",
        label: "Belastung durch Rauch, Staub, Dämpfe oder Schimmel (Wohnung oder Arbeit)?",
        name: "t7_belastung",
        options: ["nein", "ja"],
        textPlaceholder: "wodurch und seit wann",
      },
      {
        type: "textarea",
        label: "Weitere Beobachtungen zu Atmung und Belastbarkeit",
        name: "t7_weitere",
        lines: 2,
      },
      { type: "meds", label: medsQuestionLabel, name: "t7_meds", area: "Atemwege", hint: "z. B. Inhalatoren, Antihistaminika, Nasenspray, Vitamin C, NAC" },
    ],
  },
  {
    key: "t8",
    n: 9,
    short: "Immunsystem",
    title: "Immunsystem, Haut und Schleimhäute",
    fields: [
      {
        type: "check",
        label: "Bekannte Autoimmun- oder chronisch-entzündliche Erkrankungen",
        name: "t8_autoimmun",
        cols: 2,
        other: true,
        options: [
          "keine bekannt",
          "Hashimoto / Morbus Basedow",
          "Zöliakie",
          "chronisch-entzündliche Darmerkrankung",
          "Psoriasis",
          "Rheuma / Gelenkentzündungen",
          "Diabetes Typ 1",
          "Lupus",
          "Multiple Sklerose",
          "Neurodermitis",
          "Vitiligo",
          "Endometriose",
          "Fibromyalgie",
        ],
      },
      {
        type: "check",
        label: "Infektneigung und Krankheitsphasen",
        name: "t8_infekte",
        cols: 2,
        other: true,
        options: [
          "unauffällig",
          "häufige Infekte",
          "lange Erholung nach Infekten",
          "EBV / Pfeiffersches Drüsenfieber",
          "Corona / Long Covid",
          "Borreliose",
          "Mandelentzündungen",
          "Blasenentzündungen",
          "Magen-Darm-Infekte",
          "Nebenhöhlenentzündungen",
          "Pilzinfektionen",
          "Parasiten / Auslandsinfekte",
          "Herpes / Gürtelrose",
        ],
      },
      {
        type: "check",
        label: "Entzündungszeichen",
        name: "t8_entzuendung",
        cols: 2,
        other: true,
        options: [
          "keine",
          "chronisch erhöhte Entzündungswerte",
          "geschwollene Lymphknoten",
          "Fieber / erhöhte Temperatur",
          "Nachtschweiß",
          "Gelenkschmerzen",
          "Muskelschmerzen",
          "allgemeines Krankheitsgefühl",
        ],
      },
      {
        type: "check",
        label: "Allergien",
        name: "t8_allergien",
        cols: 3,
        other: true,
        options: [
          "keine bekannt",
          "Medikamente",
          "Pollen",
          "Hausstaub",
          "Tiere",
          "Nahrungsmittel",
          "Kontaktallergien",
          "Insektengift",
          "Latex",
          "Metalle",
          "Kosmetik",
        ],
      },
      {
        type: "check",
        label: "Haut, Haare und Nägel",
        name: "t8_haut",
        cols: 3,
        other: true,
        options: [
          "unauffällig",
          "Akne",
          "Rosazea",
          "Ekzeme",
          "Neurodermitis",
          "Psoriasis",
          "Juckreiz",
          "Quaddeln / Nesselsucht",
          "trockene Haut",
          "schlechte Wundheilung",
          "Hämatomneigung",
          "Hautrötungen",
          "Pigmentveränderungen",
          "Haarausfall",
          "brüchige Nägel",
        ],
      },
      {
        type: "check",
        label: "Schleimhäute",
        name: "t8_schleimhaeute",
        cols: 2,
        other: true,
        options: [
          "unauffällig",
          "trockene Augen",
          "trockener Mund",
          "Aphthen",
          "Zahnfleischbluten",
          "belegte Zunge",
          "wiederkehrende Halsschmerzen",
          "wiederkehrende Scheideninfektionen",
          "Mundgeruch",
        ],
      },
      {
        type: "radiotext",
        label: "Antibiotika in den letzten 5 Jahren",
        name: "t8_antibiotika",
        options: ["nein", "ja"],
        textPlaceholder: "wann und warum",
      },
      {
        type: "radiotext",
        label: "Cortison, Immunsuppressiva oder Biologika (aktuell oder früher)",
        name: "t8_cortison",
        options: ["nein", "ja"],
        textPlaceholder: "welche, wie lange",
      },
      { type: "meds", label: medsQuestionLabel, name: "t8_meds", area: "Immunsystem & Haut", hint: "z. B. Antihistaminika, Cortisonsalbe, Zink, Vitamin D, Omega-3" },
    ],
  },
  {
    key: "t9",
    n: 10,
    short: "Herz-Kreislauf",
    title: "Herz-Kreislauf und Gefäßsystem",
    fields: [
      {
        type: "check",
        label: "Bekannte Diagnosen in diesem Bereich",
        name: "t9_diagnosen",
        cols: 2,
        other: true,
        options: [
          "keine bekannt",
          "Bluthochdruck",
          "niedriger Blutdruck",
          "koronare Herzkrankheit / Angina pectoris",
          "Herzinfarkt",
          "Schlaganfall / TIA",
          "Herzrhythmusstörungen / Vorhofflimmern",
          "Herzklappenerkrankung",
          "Herzschwäche",
          "Fettstoffwechselstörung / hohes Cholesterin",
          "Thrombose / Embolie",
          "Krampfadern",
          "Durchblutungsstörung der Beine",
          "Gerinnungsstörung",
        ],
      },
      {
        type: "check",
        label: "Beobachtungen",
        name: "t9_symptome",
        cols: 2,
        other: true,
        options: [
          "keine",
          "Herzklopfen / Herzrasen",
          "Herzstolpern",
          "Engegefühl in der Brust",
          "Atemnot bei Belastung",
          "Schwindel beim Aufstehen",
          "Ohnmachtsneigung",
          "kalte Hände / Füße",
          "geschwollene Beine oder Knöchel",
          "schwere Beine",
          "nächtliche Wadenkrämpfe",
          "blaue Flecken ohne Grund",
          "sichtbare / schmerzende Venen",
        ],
      },
      { type: "text", label: "Blutdruckwerte, falls bekannt", name: "t9_blutdruck", placeholder: "z. B. 120/80" },
      { type: "text", label: "Ruhepuls, falls bekannt", name: "t9_puls" },
      { type: "meds", label: medsQuestionLabel, name: "t9_meds", area: "Herz-Kreislauf", hint: "z. B. Blutdrucksenker, Blutverdünner, Statine, Omega-3, Coenzym Q10" },
    ],
  },
  {
    key: "t10",
    n: 11,
    short: "Hormone",
    title: "Hormonsystem und Stoffwechsel",
    fields: [
      {
        type: "note",
        tone: "info",
        title: "Hinweis",
        text: "Bitte beantworten Sie nur, was für Sie zutrifft. Angaben zu Zyklus, Schwangerschaft oder Verhütung können Sie frei lassen.",
      },
      {
        type: "check",
        label: "Bekannte Diagnosen in diesem Bereich",
        name: "t10_diagnosen",
        cols: 2,
        other: true,
        options: [
          "keine bekannt",
          "Hashimoto",
          "Schilddrüsenunterfunktion",
          "Schilddrüsenüberfunktion",
          "Knoten / Struma",
          "Schilddrüsen-Operation",
          "PCOS",
          "Endometriose",
          "Diabetes Typ 2",
          "Prädiabetes / Insulinresistenz",
          "Gicht",
          "Nebennierenthema",
          "Osteoporose",
        ],
      },
      {
        type: "check",
        label: "Anzeichen aus dem Stoffwechsel",
        name: "t10_anzeichen",
        cols: 2,
        other: true,
        options: [
          "keine",
          "Frieren",
          "kalte Hände / Füße",
          "Haarausfall",
          "trockene Haut",
          "Gewichtszunahme trotz wenig Essen",
          "ungewollte Gewichtsabnahme",
          "Herzrasen",
          "Zittern",
          "vermehrtes Schwitzen",
          "Wassereinlagerungen",
          "Heißhunger",
          "Unterzuckergefühl / Zittrigkeit",
          "starke Müdigkeit nach dem Essen",
        ],
      },
      { type: "text", label: "Zykluslänge", name: "t10_zykluslaenge" },
      {
        type: "check",
        label: "Regelmäßigkeit",
        name: "t10_regelmaessigkeit",
        cols: 3,
        options: ["regelmäßig", "unregelmäßig", "nicht beurteilbar", "trifft nicht zu"],
      },
      { type: "text", label: "Dauer der Blutung", name: "t10_dauer" },
      {
        type: "check",
        label: "Stärke der Blutung",
        name: "t10_staerke",
        cols: 3,
        options: ["schwach", "mittel", "stark", "sehr stark"],
      },
      { type: "radiotext", label: "Regelschmerzen", name: "t10_regelschmerzen", options: ["nein", "ja"], textPlaceholder: "Stärke 0–10" },
      { type: "text", label: "Datum der letzten Periode", name: "t10_letzte_periode" },
      { type: "text", label: "Menopause / Perimenopause / Postmenopause", name: "t10_menopause" },
      {
        type: "check",
        label: "PMS, Zyklus- oder Wechseljahresbeschwerden",
        name: "t10_pms",
        cols: 2,
        other: true,
        options: [
          "Brustspannen",
          "Wassereinlagerungen",
          "Stimmungsschwankungen",
          "Reizbarkeit",
          "depressive Verstimmung",
          "Heißhunger",
          "Migräne / Kopfschmerzen",
          "Schlafprobleme",
          "Akne",
          "Unterleibsschmerzen",
          "starke Blutung",
          "Zwischen- oder Schmierblutungen",
          "Hitzewallungen",
          "zyklusabhängige Verdauungsbeschwerden",
        ],
      },
      {
        type: "check",
        label: "Verhütung aktuell oder früher",
        name: "t10_verhuetung",
        cols: 3,
        other: true,
        options: ["keine", "Pille aktuell", "Pille früher", "Hormonspirale", "Kupferspirale"],
      },
      {
        type: "check",
        label: "Hormonpräparate aktuell oder früher",
        name: "t10_hormonpraeparate",
        cols: 2,
        other: true,
        options: [
          "keine",
          "Schilddrüsenhormone",
          "Progesteron",
          "Östrogene",
          "Testosteron / DHEA",
          "Cortison",
          "Kinderwunschbehandlung",
        ],
      },
      {
        type: "textarea",
        label: "Schwangerschaften / Geburten / Fehlgeburten, falls relevant",
        name: "t10_schwangerschaften",
        lines: 2,
      },
      { type: "textarea", label: "Weitere hormonelle Beobachtungen", name: "t10_weitere", lines: 2 },
      { type: "meds", label: medsQuestionLabel, name: "t10_meds", area: "Hormone & Stoffwechsel", hint: "z. B. Schilddrüsenhormone, Pille, Metformin, Jod, Selen, Inositol" },
    ],
  },
  {
    key: "t11",
    n: 12,
    short: "Lymphe & Gewebe",
    title: "Lymph- und Bindegewebe",
    fields: [
      {
        type: "note",
        tone: "info",
        title: "Worum es hier geht",
        text: "Dieses Themenfeld fasst zusammen, was mit Wassereinlagerungen, Schwellungen, Fettverteilung und Bindegewebe zu tun hat — zum Beispiel Lipödem oder Lymphödem.",
      },
      {
        type: "check",
        label: "Bekannte Diagnosen in diesem Bereich",
        name: "t11_diagnosen",
        cols: 2,
        other: true,
        options: [
          "keine bekannt",
          "Lipödem",
          "Lymphödem",
          "Lipo-Lymphödem",
          "chronisch-venöse Insuffizienz",
          "Bindegewebsschwäche",
          "Hypermobilität / Ehlers-Danlos",
          "Fibromyalgie",
          "Lymphknoten entfernt (z. B. nach OP)",
        ],
      },
      {
        type: "check",
        label: "Beobachtungen",
        name: "t11_beobachtungen",
        cols: 2,
        other: true,
        options: [
          "keine",
          "Schweregefühl in den Beinen",
          "Schwellungen, die abends zunehmen",
          "morgens geschwollenes Gesicht",
          "Druckschmerz an Beinen oder Armen",
          "blaue Flecken schon bei leichtem Anstoßen",
          "Fettverteilung an Beinen/Armen anders als am Rumpf",
          "Dellen / Cellulite ausgeprägt",
          "Spannungsgefühl in der Haut",
          "Ringe oder Schuhe werden im Tagesverlauf eng",
          "Verhärtungen oder Narbenstränge",
        ],
      },
      {
        type: "radiotext",
        label: "Behandlung mit Lymphdrainage oder Kompression?",
        name: "t11_behandlung",
        options: ["nein", "ja", "früher"],
        textPlaceholder: "wie häufig, seit wann",
      },
      { type: "textarea", label: "Wie verändern sich Schwellungen im Tagesverlauf oder im Zyklus?", name: "t11_verlauf", lines: 2 },
      { type: "meds", label: medsQuestionLabel, name: "t11_meds", area: "Lymph- & Bindegewebe", hint: "z. B. Entwässerungsmittel, Venenmittel, Enzympräparate" },
    ],
  },
  {
    key: "t12",
    n: 13,
    short: "Nieren & Blase",
    title: "Nieren, Blase und Urogenitalsystem",
    fields: [
      {
        type: "check",
        label: "Bekannte Diagnosen in diesem Bereich",
        name: "t12_diagnosen",
        cols: 2,
        other: true,
        options: [
          "keine bekannt",
          "wiederkehrende Blasenentzündungen",
          "Nierensteine",
          "Nierenschwäche",
          "Reizblase",
          "Inkontinenz",
          "Beckenbodenschwäche",
          "Prostatabeschwerden",
          "wiederkehrende Scheideninfektionen",
        ],
      },
      {
        type: "check",
        label: "Beobachtungen",
        name: "t12_symptome",
        cols: 2,
        other: true,
        options: [
          "keine",
          "häufiges Wasserlassen",
          "nächtliches Wasserlassen",
          "Brennen beim Wasserlassen",
          "Druck im Unterbauch",
          "dunkler oder stark riechender Urin",
          "Blut im Urin",
          "Schaum im Urin",
          "wenig Urin trotz ausreichend Trinken",
          "Flankenschmerzen",
        ],
      },
      { type: "meds", label: medsQuestionLabel, name: "t12_meds", area: "Nieren & Blase", hint: "z. B. Blasentees, D-Mannose, Cranberry, Antibiotika-Dauerprophylaxe" },
    ],
  },
  {
    key: "t13",
    n: 14,
    short: "Lebensumstände",
    title: "Lebensumstände, Beruf und Umwelt",
    fields: [
      { type: "text", label: "Beruf / Tätigkeit", name: "t13_beruf" },
      {
        type: "check",
        label: "Arbeitsalltag",
        name: "t13_arbeitsalltag",
        cols: 2,
        other: true,
        options: [
          "überwiegend sitzend",
          "überwiegend stehend",
          "körperlich aktiv",
          "Schichtarbeit",
          "Nachtarbeit",
          "viel Bildschirmzeit",
          "viel Reisen",
          "hoher mentaler Druck",
          "unregelmäßige Pausen",
          "flexibel",
        ],
      },
      {
        type: "check",
        label: "Belastungen am Arbeitsplatz oder zu Hause",
        name: "t13_exposition",
        hint: "Umweltfaktoren, die biochemisch eine Rolle spielen können.",
        cols: 2,
        other: true,
        options: [
          "keine besonderen",
          "Chemikalien / Lösungsmittel",
          "Reinigungsmittel",
          "Staub / Feinstaub",
          "Farben / Lacke",
          "Metalle / Schweißrauch",
          "Pestizide",
          "Schimmel in Wohnung oder Arbeitsplatz",
          "starker Lärm",
          "Hitze oder Kälte",
          "wenig Tageslicht",
          "Infektionsrisiko durch Menschenkontakt",
        ],
      },
      { type: "textarea", label: "Wohnsituation und Umgebung (falls relevant)", name: "t13_wohnen", lines: 2 },
      { type: "text", label: "Übliche Aufstehzeit", name: "t13_aufstehzeit" },
      { type: "text", label: "Übliche Schlafenszeit", name: "t13_schlafenszeit" },
      { type: "text", label: "Übliche Essenszeiten", name: "t13_essenszeiten" },
      { type: "text", label: "Pausen im Alltag", name: "t13_pausen" },
      {
        type: "note",
        tone: "info",
        title: "Genussmittel und Substanzen",
        text: "Freiwillige Angaben, wertungsfrei — sie helfen nur dabei, Zusammenhänge richtig einzuordnen.",
      },
      { type: "text", label: "Alkohol: Häufigkeit und Menge", name: "t13_alkohol" },
      {
        type: "radiotext",
        label: "Nikotin / Rauchen",
        name: "t13_nikotin",
        options: ["nein", "gelegentlich", "regelmäßig", "früher"],
        textPlaceholder: "Menge, seit wann (z. B. Zigaretten/Tag, Vape)",
      },
      {
        type: "radiotext",
        label: "Andere Substanzen (z. B. Cannabis, weitere Freizeitsubstanzen)",
        name: "t13_substanzen",
        options: ["nein", "ja"],
        textPlaceholder: "welche, wie häufig (freiwillige Angabe)",
      },
      {
        type: "check",
        label: "Zahn- und Kiefersituation",
        name: "t13_zaehne",
        cols: 2,
        other: true,
        options: [
          "unauffällig",
          "Amalgamfüllungen",
          "andere Füllungen / Kronen",
          "Implantate",
          "Wurzelbehandlungen",
          "Zahnspange / Schiene",
          "Zahnfleischentzündung",
          "Kieferknacken oder -schmerzen",
          "Zähneknirschen",
        ],
      },
      { type: "textarea", label: "Welche Belastungen prägen Ihren Alltag aktuell?", name: "t13_belastungen", lines: 3 },
      {
        type: "textarea",
        label: "Welche Ressourcen, Routinen oder unterstützenden Personen helfen Ihnen?",
        name: "t13_ressourcen",
        lines: 3,
      },
      { type: "textarea", label: "Was lässt sich realistisch in Ihrem Alltag verändern?", name: "t13_veraenderung", lines: 2 },
    ],
  },
  {
    key: "t14",
    n: 15,
    short: "Laborwerte",
    title: "Laborwerte, Diagnostik und Befunde",
    fields: [
      {
        type: "check",
        label: "Welche Befunde oder Laborwerte liegen vor?",
        name: "t14_befunde",
        cols: 2,
        other: true,
        options: [
          "keine",
          "Blutbild",
          "Ferritin / Eisenstatus",
          "Schilddrüse",
          "Vitamin D",
          "B12 / Folat",
          "Leberwerte",
          "Nierenwerte",
          "Blutzucker / Insulin / HbA1c",
          "Lipide / Cholesterin",
          "CRP / Entzündungswerte",
          "Hormone",
          "Stuhldiagnostik",
          "Mikrobiomtest",
          "SIBO-Atemtest",
          "Laktose-/Fruktose-Atemtest",
          "Allergietest",
          "Ultraschall",
          "MRT / CT / Röntgen",
          "Arztbrief",
        ],
      },
      {
        type: "table",
        label: "Auffällige Werte, die Sie schon kennen",
        name: "t14_werte",
        hint: "Optional — nur, wenn Sie die Zahlen gerade zur Hand haben.",
        columns: ["Wert", "Ergebnis", "Datum", "Anmerkung"],
        rows: 4,
      },
      { type: "textarea", label: "Welche Diagnosen wurden bereits bestätigt oder ausgeschlossen?", name: "t14_diagnosen", lines: 3 },
      {
        type: "textarea",
        label: "Welche Befunde erscheinen Ihnen besonders wichtig?",
        name: "t14_wichtig",
        lines: 2,
      },
      {
        type: "note",
        tone: "info",
        title: "Bitte mitsenden",
        text: "Wenn möglich, fügen Sie relevante Befunde als PDF oder gut lesbares Foto bei: aktuelle Laborwerte, Verlaufslabore, Medikamentenpläne, Arztbriefe, Stuhl-/Atemtests und Facharztbefunde.",
      },
    ],
  },
  {
    key: "t15",
    n: 16,
    short: "Ziele",
    title: "Bisherige Maßnahmen, Ziele und Zusammenarbeit",
    fields: [
      {
        type: "check",
        label: "Was wurde bereits ausprobiert?",
        name: "t15_massnahmen",
        cols: 2,
        other: true,
        options: [
          "Ernährungsumstellung",
          "Supplemente",
          "Medikamente",
          "Physiotherapie",
          "Osteopathie",
          "Psychotherapie / Coaching",
          "Heilpraktiker / Naturheilkunde",
          "Fasten",
          "Darmkur",
          "Sportprogramm",
          "Schlafoptimierung",
          "Laboranalysen",
          "Stressmanagement",
          "Entspannungsverfahren",
        ],
      },
      { type: "textarea", label: "Was hat geholfen?", name: "t15_geholfen", lines: 2 },
      { type: "textarea", label: "Was hat nicht geholfen oder die Beschwerden verschlechtert?", name: "t15_nicht_geholfen", lines: 2 },
      {
        type: "textarea",
        label: "Gab es Nebenwirkungen oder Gründe, warum Sie etwas abgebrochen haben?",
        name: "t15_nebenwirkungen",
        lines: 2,
      },
      {
        type: "check",
        label: "Was möchten Sie durch die Zusammenarbeit erreichen?",
        name: "t15_ziele",
        cols: 2,
        other: true,
        options: [
          "mehr Energie",
          "bessere Verdauung",
          "weniger Beschwerden",
          "Gewichtsregulation",
          "hormonelle Balance",
          "bessere Regeneration",
          "bessere Leistungsfähigkeit",
          "weniger Entzündung oder Schmerzen",
          "Hautbild verbessern",
          "Schlaf verbessern",
          "Zyklus / PMS verbessern",
          "Laborwerte verstehen",
          "Ernährung strukturieren",
          "alltagstauglichen Plan",
          "mehr Sicherheit im Umgang mit Symptomen",
        ],
      },
      {
        type: "check",
        label: "Wie viel Zeit und Energie können Sie realistisch pro Woche investieren?",
        name: "t15_zeit",
        cols: 1,
        options: [
          "wenig: bitte möglichst einfache Schritte",
          "mittel: regelmäßige Umsetzung ist möglich",
          "viel: intensive Veränderung ist gewünscht",
          "aktuell unklar / wechselnd",
        ],
      },
      {
        type: "check",
        label: "Welche Art der Begleitung passt zu Ihnen?",
        name: "t15_begleitung",
        cols: 2,
        other: true,
        options: [
          "klare Pläne",
          "viel Hintergrundwissen",
          "kleine Schritte",
          "detaillierte Analyse",
          "regelmäßige Kontrolle",
          "flexible Empfehlungen",
          "strukturiertes Protokoll",
          "alltagstaugliche Umsetzung",
        ],
      },
      {
        type: "textarea",
        label: "Was sollte unbedingt berücksichtigt werden, damit die Empfehlungen für Sie umsetzbar sind?",
        name: "t15_beruecksichtigen",
        lines: 2,
      },
      {
        type: "textarea",
        label: "Gibt es etwas, das wichtig ist und bisher nicht abgefragt wurde?",
        name: "t15_fehlt",
        lines: 3,
      },
    ],
  },
];

/** Alle "meds"-Felder in Reihenfolge — Grundlage der automatischen Zusammenfassung. */
export const medsFields: MedsField[] = sections.flatMap((s) => s.fields.filter((f): f is MedsField => f.type === "meds"));

/** Auffangfeld in der Zusammenfassung für alles, was keinem Themenfeld zugeordnet ist. */
export const medsOther: MedsField = {
  type: "meds",
  name: "sum_meds_sonstige",
  area: "Sonstige",
  label: "Nehmen Sie weitere Medikamente oder Nahrungsergänzungsmittel, die oben noch nicht genannt wurden?",
  hint: medsHint,
};

export const optionalProtocol = {
  columns: ["Tag / Datum", "Schlaf", "Essen / Getränke", "Stuhlgang", "Symptome / Stress 0–10", "Bewegung / Besonderheiten"],
  rows: 7,
  name: "protokoll",
};

// ---- Einwilligung + Datenschutzerklärung (verbatim aus dem geprüften Stand v2.3) ----

export const consentIntro = {
  heading: "Einwilligung zur Verarbeitung meiner Gesundheitsdaten",
  paragraphs: [
    "Ich willige ausdrücklich ein, dass Milva März, Biochemische Gesundheitsberatung, Jurastraße 27-1, 72072 Tübingen-Derendingen die von mir in diesem Gesundheits- und Ernährungsfragebogen angegebenen Gesundheitsdaten (u. a. Vorerkrankungen, Symptome, Medikamenteneinnahme, Laborwerte, Ernährungs- und Lebensgewohnheiten) zum Zweck der individuellen biochemischen Gesundheits- und Ernährungsberatung verarbeitet und speichert.",
    "Sofern ich im Abschnitt „Erkrankungen in der Familie“ Angaben zu Verwandten mache, willige ich zudem ein, dass diese Angaben (ohne Namen, nur Verwandtschaftsgrad, Erkrankung und Diagnosealter) ausschließlich zur Einschätzung meiner eigenen gesundheitlichen Veranlagung verarbeitet werden.",
    "Mir ist bekannt, dass:",
  ],
  bullets: [
    "die Angabe der Gesundheitsdaten freiwillig ist; ohne diese Angaben ist eine individuelle Beratung jedoch ggf. nicht oder nur eingeschränkt möglich;",
    `ich diese Einwilligung jederzeit mit Wirkung für die Zukunft widerrufen kann, formlos per E-Mail an ${site.email}, ohne dass dadurch die Rechtmäßigkeit der bis zum Widerruf erfolgten Verarbeitung berührt wird;`,
    "weitere Informationen zur Datenverarbeitung in der ausführlichen Datenschutzerklärung (siehe unten) stehen.",
  ],
};

export const consentCheckboxes: { name: string; label: string }[] = [
  { name: "s18_bestaetigung", label: "Ich bestätige, dass ich die Angaben nach bestem Wissen gemacht habe." },
  { name: "s18_verwendung", label: "Ich bin damit einverstanden, dass die Angaben zur Vorbereitung des Ersttermins verwendet werden." },
  { name: "s18_bewusst", label: "Mir ist bewusst, dass akute oder schwerwiegende Beschwerden ärztlich abgeklärt werden müssen." },
];

type LegalBlock =
  | { type: "h4"; text: string }
  | { type: "p"; text: string }
  | { type: "ul"; items: string[] };

export const privacyNoticeBlocks: LegalBlock[] = [
  { type: "h4", text: "Datenschutzerklärung — Gesundheits- und Ernährungsfragebogen" },
  { type: "p", text: "(Stand: 13.08.2026, Rechtsgrundlage: DSGVO, BDSG in der aktuell geltenden Fassung)" },
  {
    type: "p",
    text: `1. Verantwortliche — Milva März, Biochemische Gesundheitsberatung, Jurastraße 27-1, 72072 Tübingen-Derendingen, E-Mail: ${site.email}. Ein Datenschutzbeauftragter ist nicht bestellt, da bei einer Einzelunternehmerin mit dieser Betriebsgröße gesetzlich nicht erforderlich (§ 38 BDSG).`,
  },
  {
    type: "p",
    text: "2. Zweck der Verarbeitung — Erhebung und Verarbeitung Ihrer Angaben (inkl. Gesundheitsdaten) zur Vorbereitung und Durchführung einer individuellen biochemischen Gesundheits- und Ernährungsberatung sowie zur Erstellung individueller Empfehlungen.",
  },
  {
    type: "p",
    text: "3. Kategorien personenbezogener Daten — Kontaktdaten (Name, Anschrift, E-Mail, Telefon); Gesundheitsdaten i. S. v. Art. 9 DSGVO (Vorerkrankungen, Symptome, Medikamente, Laborwerte, Ernährungs- und Lebensgewohnheiten, Beschwerden) sowie ggf. anonymisierte Angaben zu Erkrankungen bei Familienangehörigen (nur Verwandtschaftsgrad, keine Namen), sofern freiwillig angegeben.",
  },
  { type: "p", text: "4. Rechtsgrundlage" },
  {
    type: "ul",
    items: [
      "Kontaktdaten: Art. 6 Abs. 1 lit. b DSGVO (Vertrag/vorvertragliche Maßnahmen zur Beratung).",
      "Gesundheitsdaten: Art. 9 Abs. 2 lit. a DSGVO — Ihre ausdrückliche, gesonderte Einwilligung. Ohne diese Einwilligung findet keine Verarbeitung Ihrer Gesundheitsdaten statt. Zusätzlich werden die Anforderungen nach § 22 Abs. 2 BDSG (technische und organisatorische Maßnahmen) beachtet.",
    ],
  },
  {
    type: "p",
    text: "5. Empfänger / Weitergabe — Eine Weitergabe Ihrer Angaben aus diesem Fragebogen an Dritte — insbesondere an Ärzt:innen oder andere Behandelnde — erfolgt nicht. Der Fragebogen und die daraus abgeleitete Beratung bleiben ausschließlich zwischen Ihnen und Milva März. Eine Weitergabe an Dritte (z. B. Laborpartner) erfolgt nur, wenn dies für die Beratung erforderlich ist und Sie hierfür gesondert eingewilligt haben.",
  },
  {
    type: "p",
    text: "Diese Seite wird über die Website biochemische-gesundheitsberatung.com ausgeliefert (Hosting: Cloudflare) — nähere Angaben dazu finden Sie in der allgemeinen Datenschutzerklärung dieser Website, Abschnitt „Hosting, Content Delivery und Server-Logfiles“. Ihre Eingaben in diesem Fragebogen selbst werden dabei nicht an den Server übertragen (siehe Ziffer 6).",
  },
  {
    type: "p",
    text: "6. Speicherdauer — Beim Ausfüllen dieses Online-Bogens: Ihre Eingaben werden ausschließlich lokal, verschlüsselt (AES-256) in Ihrem Browser zwischengespeichert, nie an einen Server übertragen und automatisch 24 Stunden nach Ihrer letzten Eingabe von selbst gelöscht; über „Zurücksetzen“ können Sie sie jederzeit sofort löschen. Erst nachdem Sie mir den ausgedruckten/exportierten Bogen zukommen lassen — per Post oder über einen von mir bereitgestellten, passwortgeschützten und zeitlich befristeten Freigabe-Link zu einem eigens dafür angelegten Ordner in meinem eigenen, verschlüsselten Cloud-Speicher (Proton Drive), gleichwertig zur postalischen Zusendung — werden Ihre Gesundheitsdaten für die Dauer des Beratungsverhältnisses und bis zu 3 Jahre danach gespeichert, sofern keine gesetzliche Aufbewahrungspflicht entgegensteht (z. B. handels-/steuerrechtliche Fristen für Rechnungsunterlagen, § 147 AO, § 257 HGB: 6–10 Jahre). Danach werden die Daten gelöscht oder anonymisiert. Für den Freigabe-Link-Weg richte ich Ihnen den Link ein (Gültigkeit: 7 Tage) und teile ihn Ihnen per E-Mail mit; das zugehörige Passwort teile ich Ihnen über einen anderen Kanal mit (z. B. Telefon oder SMS). Laden Sie darüber bitte ausschließlich Ihren fertig ausgefüllten Fragebogen als PDF hoch. Ich lösche Ordner und Datei umgehend, sobald ich Ihre Datei heruntergeladen und übernommen habe, spätestens jedoch nach Ablauf der 7 Tage; ab der Übernahme gelten für die weitere Aufbewahrung wieder die vorstehend genannten Fristen und Löschpflichten.",
  },
  { type: "p", text: "(Hinweis: Als nicht-ärztliche Beratung gilt hier NICHT die ärztliche 10-Jahres-Dokumentationspflicht nach § 630f BGB.)" },
  {
    type: "p",
    text: `7. Ihre Rechte — Sie haben das Recht auf Auskunft (Art. 15 DSGVO), Berichtigung (Art. 16), Löschung (Art. 17), Einschränkung der Verarbeitung (Art. 18), Datenübertragbarkeit (Art. 20) sowie Widerspruch (Art. 21) gegen die Verarbeitung. Ihre Einwilligung können Sie jederzeit mit Wirkung für die Zukunft widerrufen (Art. 7 Abs. 3 DSGVO), formlos per E-Mail an ${site.email}. Sie haben zudem ein Beschwerderecht bei der zuständigen Datenschutzaufsichtsbehörde: Landesbeauftragte für den Datenschutz und die Informationsfreiheit Baden-Württemberg (LfDI BW), Königstraße 10a, 70173 Stuttgart.`,
  },
  {
    type: "p",
    text: "8. Freiwilligkeit — Die Angabe Ihrer Daten ist freiwillig. Ohne bestimmte Angaben (insbesondere Gesundheitsdaten) ist eine individuelle Beratung ggf. nicht oder nur eingeschränkt möglich.",
  },
  {
    type: "p",
    text: "9. Automatisierte Entscheidungsfindung — Es findet keine automatisierte Entscheidungsfindung oder Profiling im Sinne von Art. 22 DSGVO statt.",
  },
  {
    type: "p",
    text: "10. Datensicherheit — Ihre Daten werden durch technische und organisatorische Maßnahmen (Art. 32 DSGVO) gegen unbefugten Zugriff geschützt (z. B. verschlossene Aufbewahrung physischer Bögen, Zugriffsbeschränkung, Verschlüsselung bei digitaler Speicherung).",
  },
];
